"""
Probability of Default (PD) Models for Credit Risk Assessment

This module implements various PD models that can be used with synthetic
borrower data generated by the conditional GAN.
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_auc_score, accuracy_score
from typing import Dict, Tuple, Optional, Any
import joblib
import logging

logger = logging.getLogger(__name__)


class PDModel:
    """Base class for Probability of Default models."""
    
    def __init__(self):
        self.model = None
        self.scaler = StandardScaler()
        self.is_fitted = False
        
    def fit(self, X: np.ndarray, y: np.ndarray) -> None:
        """Fit the PD model."""
        raise NotImplementedError
        
    def predict_proba(self, X: np.ndarray) -> np.ndarray:
        """Predict probability of default."""
        raise NotImplementedError
        
    def predict(self, X: np.ndarray) -> np.ndarray:
        """Predict binary default outcome."""
        return (self.predict_proba(X) > 0.5).astype(int)


class LogisticPDModel(PDModel):
    """
    Logistic regression model for PD estimation.
    
    This is a common baseline model used in credit risk modeling.
    """
    
    def __init__(self, **kwargs):
        super().__init__()
        self.model = LogisticRegression(
            random_state=42,
            max_iter=1000,
            **kwargs
        )
        
    def fit(self, X: np.ndarray, y: np.ndarray) -> None:
        """
        Fit logistic regression PD model.
        
        Args:
            X: Borrower features [n_samples, n_features]
            y: Default labels (0=no default, 1=default) [n_samples]
        """
        # Scale features
        X_scaled = self.scaler.fit_transform(X)
        
        # Fit model
        self.model.fit(X_scaled, y)
        self.is_fitted = True
        
        logger.info("Logistic PD model fitted successfully")
        
    def predict_proba(self, X: np.ndarray) -> np.ndarray:
        """
        Predict probability of default.
        
        Args:
            X: Borrower features [n_samples, n_features]
            
        Returns:
            Probability of default [n_samples]
        """
        if not self.is_fitted:
            raise ValueError("Model must be fitted before prediction")
            
        X_scaled = self.scaler.transform(X)
        return self.model.predict_proba(X_scaled)[:, 1]  # Return P(default=1)


class GradientBoostingPDModel(PDModel):
    """
    Gradient boosting model for PD estimation.
    
    Often provides better performance than logistic regression for complex
    borrower-macro relationships.
    """
    
    def __init__(self, **kwargs):
        super().__init__()
        default_params = {
            'n_estimators': 100,
            'learning_rate': 0.1,
            'max_depth': 3,
            'random_state': 42
        }
        default_params.update(kwargs)
        
        self.model = GradientBoostingClassifier(**default_params)
        
    def fit(self, X: np.ndarray, y: np.ndarray) -> None:
        """
        Fit gradient boosting PD model.
        
        Args:
            X: Borrower features [n_samples, n_features]
            y: Default labels (0=no default, 1=default) [n_samples]
        """
        # Scale features (optional for tree-based models but can help)
        X_scaled = self.scaler.fit_transform(X)
        
        # Fit model
        self.model.fit(X_scaled, y)
        self.is_fitted = True
        
        logger.info("Gradient boosting PD model fitted successfully")
        
    def predict_proba(self, X: np.ndarray) -> np.ndarray:
        """
        Predict probability of default.
        
        Args:
            X: Borrower features [n_samples, n_features]
            
        Returns:
            Probability of default [n_samples]
        """
        if not self.is_fitted:
            raise ValueError("Model must be fitted before prediction")
            
        X_scaled = self.scaler.transform(X)
        return self.model.predict_proba(X_scaled)[:, 1]  # Return P(default=1)


class MacroConditionedPDModel(PDModel):
    """
    PD model that explicitly incorporates macroeconomic conditions.
    
    This model takes both borrower features and macro variables as input,
    allowing for direct stress testing without synthetic data generation.
    """
    
    def __init__(self, base_model: str = "logistic", **kwargs):
        super().__init__()
        
        if base_model == "logistic":
            self.model = LogisticRegression(random_state=42, max_iter=1000, **kwargs)
        elif base_model == "gbm":
            default_params = {
                'n_estimators': 100,
                'learning_rate': 0.1,
                'max_depth': 3,
                'random_state': 42
            }
            default_params.update(kwargs)
            self.model = GradientBoostingClassifier(**default_params)
        else:
            raise ValueError(f"Unsupported base model: {base_model}")
            
        self.base_model_type = base_model
        
    def fit(self, borrower_features: np.ndarray, macro_features: np.ndarray, y: np.ndarray) -> None:
        """
        Fit macro-conditioned PD model.
        
        Args:
            borrower_features: Borrower-level features [n_samples, n_borrower_features]
            macro_features: Macroeconomic features [n_samples, n_macro_features]
            y: Default labels (0=no default, 1=default) [n_samples]
        """
        # Combine borrower and macro features
        X = np.hstack([borrower_features, macro_features])
        
        # Scale features
        X_scaled = self.scaler.fit_transform(X)
        
        # Fit model
        self.model.fit(X_scaled, y)
        self.is_fitted = True
        
        logger.info(f"Macro-conditioned PD model ({self.base_model_type}) fitted successfully")
        
    def predict_proba(self, borrower_features: np.ndarray, macro_features: np.ndarray) -> np.ndarray:
        """
        Predict probability of default given borrower and macro features.
        
        Args:
            borrower_features: Borrower-level features [n_samples, n_borrower_features]
            macro_features: Macroeconomic features [n_samples, n_macro_features]
            
        Returns:
            Probability of default [n_samples]
        """
        if not self.is_fitted:
            raise ValueError("Model must be fitted before prediction")
            
        # Combine features
        X = np.hstack([borrower_features, macro_features])
        X_scaled = self.scaler.transform(X)
        
        return self.model.predict_proba(X_scaled)[:, 1]  # Return P(default=1)


def evaluate_pd_model(model: PDModel, X_test: np.ndarray, y_test: np.ndarray) -> Dict[str, float]:
    """
    Evaluate PD model performance.
    
    Args:
        model: Fitted PD model
        X_test: Test features
        y_test: Test labels
        
    Returns:
        Dictionary of evaluation metrics
    """
    if hasattr(model, 'predict_proba'):
        if isinstance(model, MacroConditionedPDModel):
            # Need to split features for macro-conditioned model
            # This assumes the test data has been properly formatted
            raise NotImplementedError("Evaluation for MacroConditionedPDModel requires feature splitting")
        else:
            y_pred_proba = model.predict_proba(X_test)
    else:
        raise ValueError("Model must have predict_proba method")
        
    y_pred = model.predict(X_test)
    
    metrics = {
        'auc': roc_auc_score(y_test, y_pred_proba),
        'accuracy': accuracy_score(y_test, y_pred),
        'default_rate_actual': np.mean(y_test),
        'default_rate_predicted': np.mean(y_pred_proba)
    }
    
    return metrics


def calculate_portfolio_metrics(pd_probs: np.ndarray, lgd: float = 0.45, ead: np.ndarray = None) -> Dict[str, float]:
    """
    Calculate portfolio-level credit risk metrics.
    
    Args:
        pd_probs: Probability of default for each borrower [n_borrowers]
        lgd: Loss Given Default (assumed constant)
        ead: Exposure at Default [n_borrowers] (if None, assumes 1.0 for all)
        
    Returns:
        Dictionary of portfolio metrics
    """
    if ead is None:
        ead = np.ones_like(pd_probs)
    
    # Expected Credit Loss = PD * LGD * EAD
    ecl_individual = pd_probs * lgd * ead
    ecl_total = np.sum(ecl_individual)
    
    # Portfolio statistics
    metrics = {
        'mean_pd': np.mean(pd_probs),
        'median_pd': np.median(pd_probs),
        'p95_pd': np.percentile(pd_probs, 95),
        'p99_pd': np.percentile(pd_probs, 99),
        'total_ecl': ecl_total,
        'mean_ecl': np.mean(ecl_individual),
        'total_exposure': np.sum(ead)
    }
    
    return metrics
