name: Deploy Slides to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: pre-release
        
    - name: Create virtual environment and install dependencies
      run: |
        python -m venv gan-env
        source gan-env/bin/activate
        pip install --upgrade pip
        pip install matplotlib numpy scipy torch jupyter
        
    - name: Build slides for GitHub Pages
      run: |
        source gan-env/bin/activate
        make github-pages
        
    - name: Create deployment directory
      run: |
        mkdir -p _site
        cp index.html _site/
        cp styles.css _site/ 2>/dev/null || true
        cp -r gan_introduction_files _site/ 2>/dev/null || true
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '_site'
        
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
